function m(b,a,c,d){b.m.nb(b.rb,a,c,d)}function n(b,a,c,d){b.m.da?m(b,a,c,d):b.m.Pe()._OnMessageFromDOM({type:"event",component:b.rb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function q(b,a,c){b.m.B(b.rb,a,c)}function v(b,a){for(const [c,d]of a)q(b,c,d)}function w(b){b.Vb||(b.m.yc(b.ee),b.Vb=!0)}window.hb=class{constructor(b,a){this.m=b;this.rb=a;this.Vb=!1;this.ee=()=>this.Pa()}ld(){}Pa(){}};
window.Cf=class{constructor(){this.gd=-1}j(){-1!==this.gd&&(self.clearTimeout(this.gd),this.gd=-1)}};"use strict";function aa(b,a){q(b,"get-element",c=>{const d=x(b,c.elementId);return a(d,c)})}function x(b,a){b=b.Ua.get(a);if(!b)throw Error(`no element with id ${a}`);return b.Tb}
window.pd=class extends self.hb{constructor(b,a){super(b,a);this.Ua=new Map;this.pb=!0;v(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=x(this,c);this.pb&&d.parentElement.removeChild(d);this.Ua.delete(c)}],["set-visible",c=>{if(this.pb){var d=this.Ua.get(c.elementId),e=d.Tb;d.Od?e.style.display=c.isVisible?"":"none":d.hf=!!c.isVisible}}],["update-position",c=>{if(this.pb){var d=this.Ua.get(c.elementId),e=d.Tb,f=this.m;e.style.left=c.left+"px";e.style.top=
c.top+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";var g=c.fontSize;null!==g&&(e.style.fontSize=g+"em");g=c.htmlIndex;d.nf=g;g=f.rd(g);g!==d.Ha&&(e.remove(),f.rc(g).appendChild(e),d.Ha=g,f.Jc());c=c.htmlZIndex;c!==d.Rc&&(d.Rc=c,f.Jc());d.Od||(d.Od=!0,d.hf&&(e.style.display=""))}}],["update-state",c=>{x(this,c.elementId);throw Error("required override");}],["focus",c=>this.Gc(c)],["set-css-style",c=>{const d=x(this,c.elementId),e=c.prop;c=c.val;e.startsWith("--")?d.style.setProperty(e,
c):d.style[e]=c}],["set-attribute",c=>{x(this,c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{x(this,c.elementId).removeAttribute(c.name)}]]);aa(this,c=>c)}Gc(b){var a=x(this,b.elementId);b.focus?a.focus():a.blur()}};"use strict";const ba=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),y=/android/i.test(navigator.userAgent);let ca=0;
function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.sf?new Promise(c=>{const d="c3_resolve_"+ca;++ca;self[d]=c;a.textContent=b.wf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}
async function da(){if(!navigator.userActivation||"undefined"===typeof OffscreenCanvas)return!1;try{let b=!1;const a=new Worker(URL.createObjectURL(new Blob(['\n\tself.addEventListener("message", () =>\n\t{\n\t\ttry {\n\t\t\tconst offscreenCanvas = new OffscreenCanvas(32, 32);\n\t\t\tconst gl = offscreenCanvas.getContext("webgl");\n\t\t\tself.postMessage(!!gl);\n\t\t}\n\t\tcatch (err)\n\t\t{\n\t\t\tconsole.warn("Feature detection worker error:", err);\n\t\t\tself.postMessage(false);\n\t\t}\n\t});'],{type:"text/javascript"})),
{get type(){b=!0}}),c=await new Promise(d=>{a.addEventListener("message",e=>{a.terminate();d(e.data)});a.postMessage("")});return b&&c}catch(b){return console.warn("Error feature detecting worker mode: ",b),!1}}let B=new Audio;
const ea={"audio/webm; codecs=opus":!!B.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!B.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!B.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!B.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!B.canPlayType("audio/mp4"),"audio/mpeg":!!B.canPlayType("audio/mpeg")};B=null;async function fa(b){b=await ha(b);return(new TextDecoder("utf-8")).decode(b)}
function ha(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const D=[];let E=0;window.RealFile=window.File;const F=[],G=new Map,H=new Map;let ia=0;const ja=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ja.push(b)};const ka=new Set(["cordova","playable-ad","instant-games"]);let la=!1;
window.Ca=class b{constructor(a){this.da=a.yf;this.xa=null;this.aa="";this.bb=a.vf;this.Hb={};this.Wa=this.ua=null;this.Ta=[];this.ma=null;this.Sd=!0;this.M=[];this.ad=[];this.bd=!1;this.fe=()=>this.Ne();this.Tc=!1;this.Ld=0;this.wb=null;this.ab=-1;this.mf=()=>this.Ye();this.Eb=new Set;this.hd=null;this.ge=[];this.u=a.he;this.Wb="file"===location.protocol.substr(0,4);if("playable-ad"===this.u||"instant-games"===this.u)this.da=!1;if("cordova"===this.u&&this.da&&y){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);
c&&90<=parseInt(c[1],10)||(this.da=!1)}this.oa()?self.chrome.webview.addEventListener("message",c=>this.Bd(c.data)):"macos-wkwebview"===this.u&&(self.C3WrapperOnMessage=c=>this.Bd(c));this.Zb=this.ra=null;"html5"!==this.u||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.B("canvas","update-size",c=>this.bf(c));this.B("canvas","set-html-layer-count",
c=>this._OnSetHTMLLayerCount(c));this.B("canvas","cleanup-html-layers",()=>this.Te());this.B("runtime","cordova-fetch-local-file",c=>this.Ue(c));this.B("runtime","create-job-worker",()=>this.Ve());this.B("runtime","send-wrapper-extension-message",c=>this.af(c));"cordova"===this.u?document.addEventListener("deviceready",()=>this.zd(a)):this.zd(a)}j(){this.zc();this.xa&&(this.xa=this.xa.onmessage=null);this.ua&&(this.ua.terminate(),this.ua=null);this.Wa&&(this.Wa.j(),this.Wa=null);for(const {canvas:a,
fb:c}of this.M)a.remove(),c.remove();this.M.length=0}ze(){return this.M[0].canvas}rd(a){return Math.min(a,this.M.length-1)}rc(a){if(0>a||a>=this.M.length)throw new RangeError("invalid canvas layer");return this.M[a].fb}De(){return ba&&"cordova"===this.u}lb(){const a=navigator.userAgent;return ba&&ka.has(this.u)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}Be(){return y}sd(){return y&&ka.has(this.u)}ud(){return"windows-webview2"===this.u||!!("preview"===this.u&&window.chrome&&window.chrome.webview&&
window.chrome.webview.postMessage)}oa(){return this.ud()||"xbox-uwp-webview2"===this.u}async zd(a){this.da&&!await da()&&(this.da=!1);"macos-wkwebview"===this.u?this.Fa({type:"ready"}):this.oa()&&(this.df(),this.ge=(await this.Se()).registeredComponentIds);if("playable-ad"===this.u){this.ra=self.c3_base64files;this.Zb={};await this.Ke();for(let d=0,e=a.eb.length;d<e;++d){var c=a.eb[d];this.Zb.hasOwnProperty(c)?a.eb[d]={sf:!0,wf:this.Zb[c]}:this.ra.hasOwnProperty(c)&&(a.eb[d]=URL.createObjectURL(this.ra[c]))}a.nc=
[]}if("nwjs"===this.u&&self.nw&&self.nw.App.manifest["c3-steam-mode"]){let d=0;this.yc(()=>{d++;document.body.style.opacity=0===d%2?"1":"0.999"})}a.uf?this.aa=a.uf:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Af&&(this.Hb=a.Af);c=new MessageChannel;this.xa=c.port1;this.xa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>this.Xe(d));this.wb=
new self.Ee(this);await oa(this.wb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.Re(a,c.port2):await this.Qe(a,c.port2)}Bc(a){a=this.Hb.hasOwnProperty(a)?this.Hb[a]:a.endsWith("/workermain.js")&&this.Hb.hasOwnProperty("workermain.js")?this.Hb["workermain.js"]:"playable-ad"===
this.u&&this.ra.hasOwnProperty(a)?this.ra[a]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async pc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.u&&this.Wb)return a=await this.Jb(d.rf?a:this.bb+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,
d)}pa(){return Math.max(window.innerWidth,1)}ga(){return Math.max(window.innerHeight,1)}yd(a){var c=this.aa,d=location.href,e=this.pa(),f=this.ga(),g=window.devicePixelRatio,h=b.kb(),k=a.Gf,l=window.cr_previewImageBlobs||this.ra,p=window.cr_previewProjectFileBlobs,r=window.cr_previewProjectFiles,t=window.cr_swClientId||"";a=a.he;var u=(new URLSearchParams(self.location.search)).has("debug"),A=this.wb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,isFullscreen:h,
projectData:k,previewImageBlobs:l,previewProjectFileBlobs:p,previewProjectFileSWUrls:r,swClientId:t,exportType:a,isDebug:u,ife:!!self.Ff,jobScheduler:{inputPort:A.Sc,outputPort:A.$c,maxNumWorkers:A.jf},supportedAudioFormats:ea,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.bb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.bb+"opus.wasm.wasm",isFileProtocol:this.Wb,isiOSCordova:this.De(),isiOSWebView:this.lb(),isWindowsWebView2:this.ud(),isAnyWebView2Wrapper:this.oa(),wrapperComponentIds:this.ge,
isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Re(a,c){const d=this.Bc(a.zf);"preview"===this.u?(this.ua=new Worker("previewworker.js",{type:"module",name:"Runtime"}),await new Promise((l,p)=>{const r=t=>{this.ua.removeEventListener("message",r);t.data&&"ok"===t.data.type?l():p()};this.ua.addEventListener("message",r);this.ua.postMessage({type:"construct-worker-init","import":(new URL(d,this.aa)).toString()})})):this.ua=await this.pc(d,this.aa,{type:"module",name:"Runtime",rf:!0});
const e=document.createElement("canvas");e.style.display="none";const f=e.transferControlToOffscreen();document.body.appendChild(e);const g=document.createElement("div");g.className="c3htmlwrap";document.body.appendChild(g);this.M.push({canvas:e,fb:g});window.c3canvas=e;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let h=a.nc||[],k=a.eb;h=await Promise.all(h.map(l=>this.Qa(l)));k=await Promise.all(k.map(l=>this.Qa(l)));if("cordova"===this.u)for(let l=0,p=a.mc.length;l<p;++l){const r=
a.mc[l],t=r[0];if(t===a.jd||"scriptsInEvents.js"===t||t.endsWith("/scriptsInEvents.js"))r[1]=await this.Qa(t)}this.ua.postMessage(Object.assign(this.yd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:f,workerDependencyScripts:h,engineScripts:k,projectScripts:a.mc,mainProjectScript:a.jd,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,f,...pa(this.wb)]);this.Ta=F.map(l=>new l(this));this.xd();qa(e);ra(g);sa(this.ma);self.c3_callFunction=(l,p)=>{var r=this.ma;return r.m.vd(r.rb,"js-invoke-function",
{name:l,params:p})};"preview"===this.u&&(self.goToLastErrorScript=()=>this.nb("runtime","go-to-last-error-script"))}async Qe(a,c){const d=document.createElement("canvas");d.style.display="none";document.body.appendChild(d);var e=document.createElement("div");e.className="c3htmlwrap";document.body.appendChild(e);this.M.push({canvas:d,fb:e});window.c3canvas=d;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ta=F.map(h=>new h(this));this.xd();qa(d);ra(e);e=a.eb.map(h=>"string"===
typeof h?(new URL(h,this.aa)).toString():h);if(Array.isArray(a.nc)){var f=[...a.nc].map(h=>h instanceof Blob?URL.createObjectURL(h):h);e.unshift(...f)}e=await Promise.all(e.map(h=>this.Qa(h)));await Promise.all(e.map(h=>z(h)));e=self.C3_ProjectScriptsStatus;f=a.jd;const g=a.mc;for(let [h,k]of g)if(k||(k=h),h===f)try{k=await this.Qa(k),await z(k),"preview"!==this.u||e[h]||this.Dd(h,"main script did not run to completion")}catch(l){this.Dd(h,l)}else if("scriptsInEvents.js"===h||h.endsWith("/scriptsInEvents.js"))k=
await this.Qa(k),await z(k);"preview"===this.u&&"object"!==typeof self.Bf.Df?(this.Ob(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.yd(a),{isInWorker:!1,messagePort:c,canvas:d,runOnStartupFunctions:ja}),sa(this.ma),this.Ad(),this.Wa=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Wa,
a))}Dd(a,c){this.Ob();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}Ad(){this.Ob()}Ob(){const a=window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async Ve(){const a=await ta(this.wb);return{outputPort:a,transferables:[a]}}bf(a){if(!this.Tc){var c=a.styleWidth+"px",d=a.styleHeight+
"px",e=a.marginLeft+"px",f=a.marginTop+"px";for(const {canvas:g,fb:h}of this.M)g.style.width=c,g.style.height=d,g.style.marginLeft=e,g.style.marginTop=f,h.style.width=c,h.style.height=d,h.style.marginLeft=e,h.style.marginTop=f,this.Sd&&(g.style.display="",h.style.display="");document.documentElement.style.setProperty("--construct-scale",a.displayScale);this.Sd=!1}}_OnSetHTMLLayerCount(a){var c=a.count,d=a.immediate,e=a.styleWidth+"px",f=a.styleHeight+"px";const g=a.marginLeft+"px",h=a.marginTop+"px";
a=[];const k=[];if(c<this.M.length)for(;this.M.length>c;){const {canvas:l,fb:p}=this.M.pop();p.remove();this.da&&!d?this.ad.push(l):l.remove()}else if(c>this.M.length)for(let l=0,p=c-this.M.length;l<p;++l)c=document.createElement("canvas"),c.classList.add("c3overlay"),this.da?(d=c.transferControlToOffscreen(),a.push(d),k.push(d)):a.push(c),document.body.appendChild(c),d=document.createElement("div"),d.classList.add("c3htmlwrap","c3overlay"),document.body.appendChild(d),c.style.width=e,c.style.height=
f,c.style.marginLeft=g,c.style.marginTop=h,d.style.width=e,d.style.height=f,d.style.marginLeft=g,d.style.marginTop=h,qa(c),ra(d),this.M.push({canvas:c,fb:d});for(const l of this.Ta)if(l instanceof window.pd&&l.pb)for(const p of l.Ua.values())e=l.m.rd(p.nf),f=p.Ha,-1!==e&&-1!==f&&e!==f&&(f=p.Tb,f.remove(),l.m.rc(e).appendChild(f),p.Ha=e);this.Jc();return{addedCanvases:a,transferables:k}}Te(){for(const a of this.ad)a.remove();this.ad.length=0}Jc(){this.bd||(this.bd=!0,this.yc(this.fe))}Ne(){this.Cd(this.fe);
this.bd=!1;let a=[];for(var c of this.Ta)if(c instanceof window.pd){var d=c.pb?[...c.Ua.values()]:null;d&&a.push(...d)}a.sort((g,h)=>{const k=g.Ha,l=h.Ha;return k!==l?k-l:g.Rc-h.Rc});let e=d=c=0,f=a.length;for(;e<f;++e){const g=a[e];g.Ha!==c&&(this.wd(c,a.slice(d,e)),c=g.Ha,d=e)}d<e&&this.wd(c,a.slice(d,e))}wd(a,c){if(!(1>=c.length||a>=this.M.length)){c=c.map(k=>k.Tb);var d=new Set(c);a=this.rc(a);for(var e=Array.from(a.children).filter(k=>d.has(k)),f=0,g=Math.min(c.length,e.length);f<g&&c[f]===e[f];++f);
for(var h=f;h<g;++h)e[h].remove();for(h=f;h<g;++h)a.appendChild(c[h])}}Pe(){if(this.da)throw Error("not available in worker mode");return this.Wa}nb(a,c,d,e,f){this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}vd(a,c,d,e,f){const g=ia++,h=new Promise((k,l)=>{H.set(g,{resolve:k,reject:l})});this.xa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===
c)return this.We(a);if("result"===c)this.Ze(a);else if("runtime-ready"===c)this.$e();else if("alert-error"===c)this.Ob(),alert(a.message);else if("creating-runtime"===c)this.Ad();else throw Error(`unknown message '${c}'`);}We(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=G.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Nb(f,!1,""+h);return}if(null===f)return g;g&&g.then?g.then(h=>this.Nb(f,!0,h)).catch(h=>
{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Nb(f,!1,""+h)}):this.Nb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Nb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.xa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ze(a){const c=a.responseId,d=a.isOk;a=a.result;const e=H.get(c);d?e.resolve(a):e.reject(a);H.delete(c)}B(a,c,d){let e=G.get(a);e||(e=new Map,G.set(a,e));
if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static Ib(a){if(F.includes(a))throw Error("DOM handler already added");F.push(a)}xd(){for(const a of this.Ta)if("runtime"===a.rb){this.ma=a;return}throw Error("cannot find runtime DOM handler");}Xe(a){this.nb("debugger","message",a)}$e(){for(const a of this.Ta)a.ld()}static kb(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||la)}static Pb(a){la=!!a}yc(a){this.Eb.add(a);
this.Ic()}Cd(a){this.Eb.delete(a);0===this.Eb.size&&this.zc()}Ic(){-1===this.ab&&0<this.Eb.size&&(this.ab=requestAnimationFrame(this.mf))}zc(){-1!==this.ab&&(cancelAnimationFrame(this.ab),this.ab=-1)}Ye(){this.ab=-1;for(const a of this.Eb)a();this.Ic()}Ea(a){this.ma.Ea(a)}Oa(a){this.ma.Oa(a)}Hc(){this.ma.Hc()}Mb(a){this.ma.Mb(a)}Ce(){return!!ea["audio/webm; codecs=opus"]}async ef(a){a=await this.vd("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}Ge(a){this.Tc=!0;this.Ld=
a}Ae(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}td(a){return!this.Ae(a)}async Qa(a){return"cordova"===this.u&&(a.startsWith("file:")||this.Wb&&this.td(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.Jb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ue(a){const c=a.filename;switch(a.as){case "text":return await this.ye(c);case "buffer":return await this.Jb(c);default:throw Error("unsupported type");
}}od(a){const c=window.cordova.file.applicationDirectory+"www/"+a;return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ye(a){a=await this.od(a);return await fa(a)}Ac(){if(D.length&&!(8<=E)){E++;var a=D.shift();this.Le(a.filename,a.xf,a.qf)}}Jb(a){return new Promise((c,d)=>{D.push({filename:a,xf:e=>{E--;this.Ac();c(e)},qf:e=>{E--;this.Ac();d(e)}});this.Ac()})}async Le(a,c,d){try{const e=await this.od(a),f=await ha(e);c(f)}catch(e){d(e)}}Bd(a){if("entered-fullscreen"===
a)b.Pb(!0),I(this.ma);else if("exited-fullscreen"===a)b.Pb(!1),I(this.ma);else if("object"===typeof a){const c=a.type;"wrapper-init-response"===c?(this.hd(a),this.hd=null):"extension-message"===c?this.nb("runtime","wrapper-extension-message",a):console.warn("Unknown wrapper message: ",a)}else console.warn("Unknown wrapper message: ",a)}af(a){this.Fa({type:"extension-message",componentId:a.componentId,messageId:a.messageId,params:a.params||[],asyncId:a.asyncId})}Fa(a){this.oa()?window.chrome.webview.postMessage(JSON.stringify(a)):
"macos-wkwebview"===this.u&&window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a))}df(){window.moveTo=(a,c)=>{this.Fa({type:"set-window-position",windowX:Math.ceil(a),windowY:Math.ceil(c)})};window.resizeTo=(a,c)=>{this.Fa({type:"set-window-size",windowWidth:Math.ceil(a),windowHeight:Math.ceil(c)})}}Se(){return this.oa()?new Promise(a=>{this.hd=a;this.Fa({type:"wrapper-init"})}):Promise.resolve()}async Ke(){const a=[];for(const [c,d]of Object.entries(this.ra))a.push(this.Je(c,d));
await Promise.all(a)}async Je(a,c){if("object"===typeof c)this.ra[a]=new Blob([c.str],{type:c.type}),this.Zb[a]=c.str;else{let d=await this.Oe(c);d||(d=this.Me(c));this.ra[a]=d}}async Oe(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}Me(a){a=this.cf(a);return this.Ie(a.data,
a.tf)}cf(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{tf:a,data:d}}Ie(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,k;for(k=h=0;h<e;++h)g[h]=a.charCodeAt(k++)|a.charCodeAt(k++)<<8|a.charCodeAt(k++)<<16|a.charCodeAt(k++)<<24;for(d&=3;d--;)f[k]=a.charCodeAt(k),++k;return new Blob([f],
{type:c})}};"use strict";const J=self.Ca,ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),K={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},wa={dispatchRuntimeEvent:!0};function xa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function ya(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}
async function L(b){b=URL.createObjectURL(b);try{return await ya(b)}finally{URL.revokeObjectURL(b)}}function za(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function Aa(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await L(b);var d=await za(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await L(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await L(b)}
function Ba(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Da=new Set(["input","textarea","datalist","select"]),Ea=new Set(["canvas","body","html"]);function M(b){b.target.tagName&&Ea.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Fa(b){b.target.tagName&&b.target.classList.contains("c3htmlwrap")&&b.preventDefault()}function Ga(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await L(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await Aa(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Ha=!1;document.addEventListener("pause",()=>Ha=!0);document.addEventListener("resume",()=>Ha=!1);function qa(b){b.addEventListener("selectstart",M);b.addEventListener("gesturehold",M);b.addEventListener("pointerdown",M)}function ra(b){b.addEventListener("selectstart",Fa);b.addEventListener("gesturehold",Fa);b.addEventListener("touchstart",Fa)}function sa(b){b.Kd=!0;b.Wc=b.m.pa();b.xb=b.m.ga()}
function I(b){if(!b.ka){var a=J.kb();a&&"any"!==b.ed&&Ia(b);m(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.pa(),innerHeight:b.ga()})}}async function Ja(b){await Promise.all(b.webfonts.map(async a=>{a=new FontFace(a.name,`url('${a.url}')`);document.fonts.add(a);await a.load()}))}
async function Ka(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function La(b){return await self.C3_GetSvgImageSize(b.blob)}function Ma(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}
function Na(b){self.setTimeout(()=>{b.Jd=!0},1E3);"cordova"===b.m.u?(document.addEventListener("pause",()=>Oa(b,!0)),document.addEventListener("resume",()=>Oa(b,!1))):document.addEventListener("visibilitychange",()=>Oa(b,"hidden"===document.visibilityState));b.cc=!("hidden"!==document.visibilityState&&!Ha);return{isSuspended:b.cc}}
function Pa(b){b.Fd||(b.Fd=!0,window.addEventListener("deviceorientation",a=>{b.ka||m(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},K)}),window.addEventListener("deviceorientationabsolute",a=>{b.ka||m(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},K)}))}
function Qa(b){b.Ed||(b.Ed=!0,window.addEventListener("devicemotion",a=>{if(!b.ka){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});m(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},K)}}))}async function Ra(b){await xa(b.url)}
function Sa(b,a){b.Md=a.message;-1===b.Nc&&(b.Nc=setTimeout(()=>{b.Nc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.Md)},250))}function Ta(b,a){console.warn("[Construct] Fullscreen request failed: ",a);m(b,"fullscreenerror",{isFullscreen:J.kb(),innerWidth:b.pa(),innerHeight:b.ga()})}
function Oa(b,a){b.cc!==a&&((b.cc=a)?b.m.zc():b.m.Ic(),m(b,"visibilitychange",{hidden:a}),!a&&b.m.lb()&&(b=()=>{document.scrollingElement.scrollTop=0;document.scrollingElement.scrollLeft=0},setTimeout(b,50),setTimeout(b,100),setTimeout(b,250),setTimeout(b,500)))}
function Ua(b,a,c){"Backspace"===c.key&&M(c);if(b.m.oa()){var d=["r","p","f","g","u"];(["F3","F5","F7"].includes(c.key)||c.ctrlKey&&d.includes(c.key))&&c.preventDefault()}b.ka||(d=ua.get(c.code)||c.code,n(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},K))}
function N(b,a,c,d){b.ka||c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents||n(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}
function O(b,a,c){if(!b.ka){var d=0;"mouse"===c.pointerType&&(d=b.Yc);n(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Aa,pageX:c.pageX,pageY:c.pageY+b.Aa,movementX:c.movementX||0,movementY:c.movementY||0,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,twist:c.twist||0,timeStamp:c.timeStamp},K);"mouse"===c.pointerType&&
(b.Yc=c.buttons)}}function Va(b,a,c){document.body.style.position="";document.body.style.overflow="";document.body.style.transform="";b.Aa=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.position="absolute",document.body.style.overflow="visible",document.body.style.transform=`translateY(${-a}px)`,b.Aa=a))}}
function Wa(b,a,c,d){const e=b.pa(),f=b.ga();b.cb=-1;e!=a||f!=c?m(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.kb()}):10>d&&Xa(b,e,f,d+1)}function Xa(b,a,c,d){-1!==b.cb&&clearTimeout(b.cb);b.cb=setTimeout(()=>Wa(b,a,c,d),48)}
function Ia(b){b=b.ed;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ya(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
J.Ib(class extends self.hb{constructor(b){super(b,"runtime");this.Kd=!1;this.cb=-1;this.ed="any";this.cc=this.Ed=this.Fd=!1;this.jc=document.createElement("div");this.jc.className="c3-screen-reader-text";this.jc.setAttribute("aria-live","polite");document.body.appendChild(this.jc);this.Ja=null;this.ka=!1;this.Md="";this.Nc=-1;this.Jd=!1;this.Wc=b.pa();this.xb=b.ga();this.Aa=this.Gb=0;b.B("runtime","invoke-download",c=>{const d=c.url;c=c.filename;const e=document.createElement("a"),f=document.body;
e.textContent=c;e.href=d;e.download=c;f.appendChild(e);e.click();f.removeChild(e)});b.B("runtime","load-webfonts",c=>Ja(c));b.B("runtime","raster-svg-image",c=>Ka(c));b.B("runtime","get-svg-image-size",c=>La(c));b.B("runtime","set-target-orientation",c=>{this.ed=c.targetOrientation});b.B("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.B("runtime","post-to-debugger",c=>Ma(c));b.B("runtime","go-to-script",c=>Ma(c));b.B("runtime","before-start-ticking",()=>Na(this));b.B("runtime",
"debug-highlight",c=>{if(c.show){this.Ja||(this.Ja=document.createElement("div"),this.Ja.id="inspectOutline",document.body.appendChild(this.Ja));var d=this.Ja;d.style.display="";d.style.left=c.left-1+"px";d.style.top=c.top-1+"px";d.style.width=c.width+2+"px";d.style.height=c.height+2+"px";d.textContent=c.name}else this.Ja&&(this.Ja.style.display="none")});b.B("runtime","enable-device-orientation",()=>Pa(this));b.B("runtime","enable-device-motion",()=>Qa(this));b.B("runtime","add-stylesheet",c=>Ra(c));
b.B("runtime","script-create-worker",c=>{const d=c.port2;(new Worker(c.url,c.opts)).postMessage({type:"construct-worker-init",port2:d},[d])});b.B("runtime","alert",c=>this.Ec(c));b.B("runtime","screen-reader-text",c=>{var d=c.type;"create"===d?(d=document.createElement("p"),d.id="c3-sr-"+c.id,d.textContent=c.text,this.jc.appendChild(d)):"update"===d?(d=document.getElementById("c3-sr-"+c.id))?d.textContent=c.text:console.warn(`[Construct] Missing screen reader text with id ${c.id}`):"release"===d?
(d=document.getElementById("c3-sr-"+c.id))?d.remove():console.warn(`[Construct] Missing screen reader text with id ${c.id}`):console.warn(`[Construct] Unknown screen reader text update '${d}'`)});b.B("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.B("runtime","set-exporting-to-video",c=>{this.ka=!0;const d=document.createElement("h1");d.id="exportToVideoMessage";d.textContent=c.message;document.body.prepend(d);document.body.classList.add("exportingToVideo");
this.m.ze().style.display="";this.m.Ge(c.duration)});b.B("runtime","export-to-video-progress",c=>Sa(this,c));b.B("runtime","exported-to-video",c=>{window.pf({type:"exported-video",arrayBuffer:c.arrayBuffer,contentType:c.contentType,time:c.time})});b.B("runtime","exported-to-image-sequence",c=>{window.pf({type:"exported-image-sequence",blobArr:c.blobArr,time:c.time,gif:c.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",c=>{const d=c.target;a.has(d.tagName.toLowerCase())||
Ba(d)||c.preventDefault()});window.addEventListener("selectstart",M);window.addEventListener("gesturehold",M);window.addEventListener("touchstart",M,{passive:!1});window.addEventListener("pointerdown",M,{passive:!1});this.Yc=0;window.addEventListener("mousedown",c=>{1===c.button&&c.preventDefault()});window.addEventListener("mousewheel",Ga,{passive:!1});window.addEventListener("wheel",Ga,{passive:!1});window.addEventListener("resize",()=>{a:{if(!this.ka&&this.Kd){var c=this.pa();var d=this.ga();if(this.m.sd()){if(this.Jd){if(this.Wc===
c&&d<this.xb){this.Gb=this.xb-d;Va(this,this.xb,this.Gb);c=void 0;break a}0<this.Gb&&(this.Gb=0,Va(this,d,this.Gb))}this.Wc=c;this.xb=d}m(this,"window-resize",{innerWidth:c,innerHeight:d,devicePixelRatio:window.devicePixelRatio,isFullscreen:J.kb()});this.m.lb()&&(-1!==this.cb&&clearTimeout(this.cb),Wa(this,c,d,0))}c=void 0}return c});window.addEventListener("fullscreenchange",()=>I(this));window.addEventListener("webkitfullscreenchange",()=>I(this));window.addEventListener("mozfullscreenchange",()=>
I(this));window.addEventListener("fullscreenerror",c=>Ta(this,c));window.addEventListener("webkitfullscreenerror",c=>Ta(this,c));window.addEventListener("mozfullscreenerror",c=>Ta(this,c));if(b.lb()){if(window.visualViewport){let c=Infinity;window.visualViewport.addEventListener("resize",()=>{const d=window.visualViewport.height;d>c&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0);c=d})}else window.addEventListener("focusout",()=>{{const e=document.activeElement;if(e){var c=
e.tagName.toLowerCase();var d=new Set("email number password search tel text url".split(" "));c="textarea"===c?!0:"input"===c?d.has(e.type.toLowerCase()||"text"):Ba(e)}else c=!1}c||(document.scrollingElement.scrollTop=0)});document.documentElement.setAttribute("ioswebview","")}this.Xa=new Set;this.ac=new WeakSet;this.wa=!1}ld(){window.addEventListener("focus",()=>{m(this,"window-focus",null,wa)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=
!1}m(this,"window-blur",{parentHasFocus:a},wa);this.Yc=0});window.addEventListener("focusin",a=>{a=a.target;(Da.has(a.tagName.toLowerCase())||Ba(a))&&m(this,"keyboard-blur",null,wa)});window.addEventListener("keydown",a=>Ua(this,"keydown",a));window.addEventListener("keyup",a=>Ua(this,"keyup",a));window.addEventListener("mousedown",a=>N(this,"mousedown",a,va));window.addEventListener("mousemove",a=>N(this,"mousemove",a,va));window.addEventListener("mouseup",a=>N(this,"mouseup",a,va));window.addEventListener("dblclick",
a=>N(this,"dblclick",a,K));window.addEventListener("wheel",a=>{this.ka||m(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Aa,pageX:a.pageX,pageY:a.pageY+this.Aa,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},K)});window.addEventListener("pointerdown",a=>{window!==window.top&&window.focus();Ya(a.target)&&document.activeElement&&!Ya(document.activeElement)&&document.activeElement.blur();O(this,"pointerdown",a)});this.m.da&&"undefined"!==typeof window.onpointerrawupdate&&
self===self.top?window.addEventListener("pointerrawupdate",a=>{O(this,"pointermove",a)}):window.addEventListener("pointermove",a=>O(this,"pointermove",a));window.addEventListener("pointerup",a=>O(this,"pointerup",a));window.addEventListener("pointercancel",a=>O(this,"pointercancel",a));const b=()=>this.Hc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",
b,!0);this.m.Be()&&!this.m.sd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ga(),navigator.virtualKeyboard.boundingRect.height)}));this.m.lb()&&(document.scrollingElement.scrollTop=0,document.scrollingElement.scrollLeft=0)}pa(){return this.m.pa()}ga(){return this.m.ga()}Hc(){var b=[...this.Xa];this.Xa.clear();if(!this.wa)for(const a of b)(b=a.play())&&b.catch(()=>{this.ac.has(a)||this.Xa.add(a)})}Ea(b){if("function"!==
typeof b.play)throw Error("missing play function");this.ac.delete(b);let a;try{a=b.play()}catch(c){this.Xa.add(b);return}a&&a.catch(()=>{this.ac.has(b)||this.Xa.add(b)})}Oa(b){this.Xa.delete(b);this.ac.add(b)}Mb(b){this.wa=!!b}Ec(b){alert(b.message)}});"use strict";
async function oa(b){if(b.ff)throw Error("already initialised");b.ff=!0;var a=b.ya.Bc(("playable-ad"===b.ya.u?b.ya.bb:"")+"dispatchworker.js");b.Mc=await b.ya.pc(a,b.qb,{name:"DispatchWorker"});a=new MessageChannel;b.Sc=a.port1;b.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.$c=await ta(b)}function pa(b){return[b.Sc,b.$c]}
async function ta(b){const a=b.Td.length;var c=b.ya.Bc(("playable-ad"===b.ya.u?b.ya.bb:"")+"jobworker.js");c=await b.ya.pc(c,b.qb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Td.push(c);return e.port1}
self.Ee=class{constructor(b){this.ya=b;this.qb=b.aa;this.qb="preview"===b.u?this.qb+"workers/":this.qb+b.bb;this.jf=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Td=[];this.$c=this.Sc=null}};"use strict";window.C3_Is_Supported&&(window.c3_runtimeInterface=new self.Ca({yf:!0,zf:"workermain.js",eb:["scripts/c3runtime.js"],mc:[],jd:"",vf:"scripts/",nc:[],he:"html5"}));"use strict";
async function Za(b,a){a=a.type;let c=!0;0===a?c=await $a():1===a&&(c=await ab());m(b,"permission-result",{type:a,result:c})}async function $a(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function ab(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Ca.Ib(class extends self.hb{constructor(b){super(b,"touch");q(this,"request-permission",a=>Za(this,a))}});"use strict";function bb(){}
function cb(b){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>m(b,"sw-message",a.data))}
function db(b){b=b.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}
self.Ca.Ib(class extends self.hb{constructor(b){super(b,"browser");this.u="";v(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isConstructArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>
cb(this)],["alert",a=>this.Ec(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Gc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>db(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?
screen.webkitUnlockOrientation():screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var c=a.type;if("back"===c)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===c)window.history.forward();else if("reload"===c)location.reload();else if("url"===c){c=a.url;const d=a.target;a=a.exportType;self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,
"_system"):"preview"===a||this.m.oa()?window.open(c,"_blank"):this.Ef||(2===d?window.top.location=c:1===d?window.parent.location=c:window.location=c)}else"new-window"===c&&(c=a.url,a=a.tag,self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(c,"_system"):window.open(c,a))}],["request-fullscreen",a=>{if(this.m.oa()||"macos-wkwebview"===this.u)self.Ca.Pb(!0),this.m.Fa({type:"set-fullscreen",fullscreen:!0});else{const c={navigationUI:"auto"};a=a.navUI;1===a?c.navigationUI="hide":2===
a&&(c.navigationUI="show");a=document.documentElement;let d;a.requestFullscreen?d=a.requestFullscreen(c):a.mozRequestFullScreen?d=a.mozRequestFullScreen(c):a.msRequestFullscreen?d=a.msRequestFullscreen(c):a.webkitRequestFullScreen&&(d="undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):a.webkitRequestFullScreen());d instanceof Promise&&d.catch(bb)}}],["exit-fullscreen",()=>{if(this.m.oa()||"macos-wkwebview"===this.u)self.Ca.Pb(!1),this.m.Fa({type:"set-fullscreen",
fullscreen:!1});else{let a;document.exitFullscreen?a=document.exitFullscreen():document.mozCancelFullScreen?a=document.mozCancelFullScreen():document.msExitFullscreen?a=document.msExitFullscreen():document.webkitCancelFullScreen&&(a=document.webkitCancelFullScreen());a instanceof Promise&&a.catch(bb)}}],["set-hash",a=>{location.hash=a.hash}],["set-document-css-style",a=>{const c=a.prop,d=a.value;var e=a.selector;a=a["is-all"];try{if(e)if(a)var f=Array.from(document.querySelectorAll(e));else{var g=
document.querySelector(e);f=g?[g]:[]}else f=[document.documentElement];e=f;for(const h of e)c.startsWith("--")?h.style.setProperty(c,d):h.style[c]=d}catch(h){console.warn("[Browser] Failed to set style: ",h)}}],["get-document-css-style",a=>{{const d=a.prop;a=a.selector;try{const e=document.querySelector(a);var c=e?{isOk:!0,result:window.getComputedStyle(e).getPropertyValue(d)}:{isOk:!1}}catch(e){console.warn("[Browser] Failed to get style: ",e),c={isOk:!1}}}return c}],["set-window-size",a=>{window.resizeTo(a.windowWidth,
a.windowHeight)}],["set-window-position",a=>{window.moveTo(a.windowX,a.windowY)}]]);window.addEventListener("online",()=>{m(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{m(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{m(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{m(this,"backbutton")})}Ec(b){alert(b.message)}Gc(b){b=b.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?nw.Window.get():
null;b?a.focus():a.blur()}else b?window.focus():window.blur()}});"use strict";const eb=180/Math.PI;
async function fb(b,a){if(a.isiOSCordova||a.isSafari)b.ec=!0;b.fd=a.timeScaleMode;b.Yd=["equalpower","HRTF","soundfield"][a.panningModel];b.Id=["linear","inverse","exponential"][a.distanceModel];b.Zd=a.refDistance;b.Xd=a.maxDistance;b.ae=a.rolloffFactor;if(b.m.Tc)b.ec=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.m.Ld)});else{var c={latencyHint:a.latencyHint};b.de||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");ib(b);b.g.onstatechange=()=>{"running"!==b.g.state&&ib(b);m(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Sa=b.g.createGain();b.Sa.connect(b.g.destination);c=a.listenerPos;b.$[0]=c[0];b.$[1]=c[1];b.$[2]=c[2];b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(...b.ba);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,
d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function jb(b,a){var c=a.originalUrl,d=a.url;const e=a.type,f=a.isMusic,g=a.tags,h=a.isLooping,k=a.vol,l=a.pos,p=a.panning,r=a.stereoPan;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Ud=g.slice(0);kb(b,g);try{b.R=await lb(b,c,d,e,g,f);if(p){Q(b.R,!0);var u=b.R,A=p.innerAngle,ma=p.outerAngle,na=p.outerGain;if(u.vb){mb(u,p.x,p.y,p.z,p.angle);var C=self.gb.He;u.sa[0]!==C(A)&&
(u.sa[0]=C(A),u.F.coneInnerAngle=C(A));u.sa[1]!==C(ma)&&(u.sa[1]=C(ma),u.F.coneOuterAngle=C(ma));u.sa[2]!==na&&(u.sa[2]=na,u.F.coneOuterGain=na)}p.hasOwnProperty("uid")&&(b.R.qa=p.uid)}else"number"===typeof r&&0!==r?(R(b.R,!0),nb(b.R,r)):(Q(b.R,!1),R(b.R,!1));b.R.Play(h,k,l,t)}catch(zb){console.error("[Construct] Audio: error starting playback: ",zb);return}finally{c=g.join(" ");d=b.Db.get(c);if(!d)throw Error("expected pending tag");d.kd--;0===d.kd&&(d.resolve(),b.Db.delete(c))}w(b)}
async function ob(b,a){var c=a.tags;const d=a.vol,e=a.duration;a=a.stopOnEnd;await pb(b,c);for(const h of S(b,c))if(!h.va){c=h.G.gain;c.cancelScheduledValues(0);var f=h.v.g.currentTime,g=f+e;c.setValueAtTime(c.value,f);c.linearRampToValueAtTime(d,g);h.Ma=d;h.Va=g;h.ce=a}T(b)}async function qb(b,a){const c=a.tags;a=a.rate;await pb(b,c);for(const d of S(b,c))d.la!==a&&(d.la=a,d.Ga())}async function rb(b,a){const c=a.tags;a=a.pos;await pb(b,c);for(const d of S(b,c))d.vc(a)}
async function sb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await lb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function tb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ia.indexOf(a),-1!==a&&b.ia.splice(a,1)}
async function ub(b,a){const c=a.type;var d=a.hasOwnProperty("tags")?a.tags:[a.tag];const e=a.params;let f;if("convolution"===c)try{f=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(k){console.log("[Construct] Audio: error loading convolution: ",k);return}for(const k of d){if("filter"===c)d=new self.ne(b,...e);else if("delay"===c)d=new self.le(b,...e);else if("convolution"===c){var g=d=new self.ke(b,f.ha,...e),h=a.bufferType;g.Gd=a.bufferOriginalUrl;g.Hd=h}else if("flanger"===c)d=
new self.oe(b,...e);else if("phaser"===c)d=new self.qe(b,...e);else if("gain"===c)d=new self.pe(b,...e);else if("stereopan"===c)d=new self.se(b,...e);else if("tremolo"===c)d=new self.te(b,...e);else if("ringmod"===c)d=new self.re(b,...e);else if("distortion"===c)d=new self.me(b,...e);else if("compressor"===c)d=new self.je(b,...e);else if("analyser"===c)d=new self.ie(b,...e);else throw Error("invalid effect type");g=b;h=k;h=h.toLowerCase();let l=g.ja.get(h);l||(l=[],g.ja.set(h,l));d.Rd=l.length;d.dd=
h;l.push(d);vb(g,h)}wb(b)}
async function xb(b,a){const c=a.saveLoadMode;if(3!==c){var d=[];for(var e of b.H)e.Ba()&&1===c||!e.Ba()&&2===c?d.push(e):e.j();b.H=d}for(const f of b.ja.values())for(const g of f)g.j();b.ja.clear();b.kc=a.timeScale;b.Oc=a.gameTime;d=a.listenerPos;b.$[0]=d[0];b.$[1]=d[1];b.$[2]=d[2];b.g.listener.setPosition(d[0],d[1],d[2]);d=a.listenerOrientation;if(Array.isArray(d)){for(e=0;6>e;++e)b.ba[e]=d[e];b.g.listener.setOrientation(...b.ba)}b.wa=a.isSilent;b.m.Mb(b.wa);b.$b=a.masterVolume;b.Sa.gain.value=
b.$b;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(g=>ub(b,g))));await Promise.all(d);await Promise.all(a.playing.map(f=>yb(b,f,c)));T(b)}
async function Ab(b,a){try{const c=b.g.suspend(a.time);b.Qd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.m.nb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Bb(d)),b.Qd=!0);await c}catch(c){Bb(c)}}
function ib(b){b.Ub||(b.Qc=!1,window.addEventListener("pointerup",b.za,!0),window.addEventListener("touchend",b.za,!0),window.addEventListener("click",b.za,!0),window.addEventListener("keydown",b.za,!0),b.Ub=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ia)if(g.jb()===c)return await Cb(g),g;if(f)return null;if(e&&(b.ec||b.Pd)){f=0;for(let h=0,k=b.ia.length;h<k;++h)g=b.ia[h],b.ia[f]=g,g.Ba()?g.j():++f;b.ia.length=f}f="audio/webm; codecs=opus"===d&&!b.de;e&&f&&(b.Pd=!0);c=!e||b.ec||f?new self.we(b,a,c,d,e,f):new self.ue(b,a,c,d,e);b.ia.push(c);await Cb(c);b.Wd.has(a)||(m(b,"buffer-metadata",{originalUrl:a,duration:c.fa()}),b.Wd.add(a));return c}
function Db(b,a){return b===a||b.normalize().toLowerCase()===a.normalize().toLowerCase()}function Eb(b,a){return(a=b.ja.get(a.toLowerCase()))?a[0].N():b.ea()}function vb(b,a){a=a.toLowerCase();let c=b.ea();var d=b.ja.get(a);if(d&&d.length){c=d[0].N();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ea()):e.U(d[f+1].N())}}for(const f of Fb(b,a))d=c,e=f.ca||f.F||f.G,e.disconnect(),e.connect(d);b.Ka&&b.Xc===a&&(b.Ka.disconnect(),b.Ka.connect(c))}
function*Fb(b,a){if(a)for(const c of b.H)Db(0<c.na.length?c.na[0]:"",a)&&(yield c);else b.R&&!b.R.O()&&(yield b.R)}function Gb(b,a,c){return c?b.m.ef(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Hb(b,a){let c=0;for(let d=0,e=b.H.length;d<e;++d){const f=b.H[d];b.H[c]=f;f.P===a?f.j():++c}b.H.length=c}
function*S(b,a){if(0<a.length)for(const d of b.H){a:{b=d.na;var c=a;for(const e of c){c=!1;for(const f of b)if(Db(f,e)){c=!0;break}if(!c){b=!1;break a}}b=!0}b&&(yield d)}else b.R&&!b.R.O()&&(yield b.R)}async function lb(b,a,c,d,e,f){for(const g of b.H)if(g.jb()===c&&(g.oc()||f))return g.na=e,g;a=await P(b,a,c,d,f);e="html5"===a.Kc?new self.ve(a.v,a,e):new self.xe(a.v,a,e);b.H.push(e);return e}
function kb(b,a){a=a.join(" ");let c=b.Db.get(a);if(!c){let d=null;c={kd:0,promise:new Promise(e=>d=e),resolve:d};b.Db.set(a,c)}c.kd++}function pb(b,a){return(b=b.Db.get((0===a.length?b.Ud:a).join(" ")))?b.promise:Promise.resolve()}function T(b){if(0<b.Ra.size)w(b);else for(const a of b.H)if(!a.I&&!a.O()){w(b);break}}function Ib(b,a,c,d){m(b,"trigger",{type:a,tags:c,aiid:d})}function wb(b){b.Uc||(b.Uc=!0,Promise.resolve().then(()=>Jb(b)))}
function Jb(b){const a={};for(const [c,d]of b.ja)a[c]=d.map(e=>e.ib());m(b,"fxstate",{fxstate:a});b.Uc=!1}
async function yb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tags,k=a.isLooping,l=a.volume,p=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await lb(b,d,e,f,h,g)}catch(r){console.error("[Construct] Audio: error loading audio state: ",r);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.Za[0]=f[0],b.Za[1]=f[1],b.Za[2]=f[2],f=d.orient,b.Ya[0]=f[0],b.Ya[1]=f[1],b.Ya[2]=f[2],e.setPosition(...b.Za),e.setOrientation(...b.Ya),b.sa[0]=d.cia,b.sa[1]=d.coa,b.sa[2]=
d.cog,e.coneInnerAngle=d.cia,e.coneOuterAngle=d.coa,e.coneOuterGain=d.cog,b.qa=d.uid):Q(b,!1);b=c;d=a.stereoPan;"number"!==typeof d?R(b,!1):(R(b,!0),nb(b,d));c.Play(k,l,p,0);a.isPlaying||c.mb();c.Dc(a)}}}function Bb(b){console.error("[Audio] Offline rendering error: ",b)}
self.gb=class extends self.hb{constructor(b){super(b,"audio");this.Sa=this.g=null;this.Ub=this.Qc=!1;this.za=()=>{if(!this.Qc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ub&&(this.Qc=!0,window.removeEventListener("pointerup",this.za,!0),window.removeEventListener("touchend",this.za,!0),window.removeEventListener("click",this.za,!0),window.removeEventListener("keydown",
this.za,!0),this.Ub=!1)}};this.ia=[];this.H=[];this.R=null;this.Ud=[];this.Wd=new Set;this.Vd=-1;this.Db=new Map;this.$b=1;this.wa=!1;this.fd=0;this.kc=1;this.Oc=0;this.Yd="HRTF";this.Id="inverse";this.Zd=600;this.Xd=1E4;this.ae=1;this.$=[0,0,0];this.ba=[0,0,-1,0,1,0];this.Pd=this.ec=!1;this.de=this.m.Ce();this.ja=new Map;this.Ra=new Set;this.Qd=this.Uc=!1;this.Xc="";this.Ka=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ka&&this.Ka.disconnect();this.Xc=c.toLowerCase();this.Ka=this.g.createMediaStreamSource(a);
this.Ka.connect(Eb(this,this.Xc))};this.Sb=null;self.C3Audio_GetOutputStream=()=>{this.Sb||(this.Sb=this.g.createMediaStreamDestination(),this.Sa.connect(this.Sb));return this.Sb.stream};self.C3Audio_DOMInterface=this;v(this,[["create-audio-context",a=>fb(this,a)],["play",a=>jb(this,a)],["stop",a=>{a=a.tags;for(const c of S(this,a))c.Da()}],["stop-all",()=>{for(const a of this.H)a.Da()}],["set-paused",a=>{const c=a.tags;a=a.paused;for(const d of S(this,c))a?d.mb():d.Lb();T(this)}],["set-volume",a=>
{const c=a.tags;a=a.vol;for(const d of S(this,c))U(d,a)}],["fade-volume",a=>ob(this,a)],["set-master-volume",a=>{this.$b=a.vol;this.Sa.gain.value=this.$b}],["set-muted",a=>{const c=a.tags;a=a.isMuted;for(const d of S(this,c))Kb(d,a)}],["set-silent",a=>{this.wa=a.isSilent;this.m.Mb(this.wa);for(const c of this.H)c.Qb()}],["set-looping",a=>{const c=a.tags;a=a.isLooping;for(const d of S(this,c))d.wc(a)}],["set-playback-rate",a=>qb(this,a)],["set-stereo-pan",a=>{const c=a.tags;a=a.p;for(const d of S(this,
c))R(d,!0),nb(d,a)}],["seek",a=>rb(this,a)],["preload",a=>sb(this,a)],["unload",a=>tb(this,a)],["unload-all",()=>{for(const a of this.ia)a.j();this.ia.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.H)c.xc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>ub(this,a)],["set-effect-param",a=>{var c=a.tags;const d=a.index,e=a.param,f=a.value,g=a.ramp;a=a.time;for(const h of c)c=this.ja.get(h.toLowerCase()),!c||0>d||d>=c.length||c[d].Z(e,
f,g,a);wb(this)}],["remove-effects",a=>{a=a.tags;for(const c of a){a=c.toLowerCase();const d=this.ja.get(a);if(!d||!d.length)break;for(const e of d)e.j();this.ja.delete(a);vb(this,a)}}],["tick",a=>{this.kc=a.timeScale;this.Oc=a.gameTime;this.Vd=a.tickCount;if(0!==this.fd)for(var c of this.H)c.Ga();!(c=a.listenerPos)||this.$[0]===c[0]&&this.$[1]===c[1]&&this.$[2]===c[2]||(this.$[0]=c[0],this.$[1]=c[1],this.$[2]=c[2],this.g.listener.setPosition(c[0],c[1],c[2]));if((c=a.listenerOrientation)&&(this.ba[0]!==
c[0]||this.ba[1]!==c[1]||this.ba[2]!==c[2]||this.ba[3]!==c[3]||this.ba[4]!==c[4]||this.ba[5]!==c[5])){for(let d=0;6>d;++d)this.ba[d]=c[d];this.g.listener.setOrientation(...this.ba)}for(const d of a.instPans){a=d.uid;for(const e of this.H)e.qa===a&&mb(e,d.x,d.y,d.z,d.angle)}}],["load-state",a=>xb(this,a)],["offline-render-audio",a=>Ab(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}V(){return this.g}ea(){return this.Sa}GetAudioContextExtern(){return this.V()}GetDestinationNodeExtern(){return this.ea()}Kb(){return this.wa}Ea(b){this.m.Ea(b)}Oa(b){this.m.Oa(b)}Pa(){for(var b of this.Ra)b.Pa();
b=this.g.currentTime;for(var a of this.H)a.Pa(b);a=this.H.filter(c=>!c.I&&!c.O()).map(c=>c.ib());m(this,"state",{tickCount:this.Vd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ra].map(c=>({tag:c.dd,index:c.Rd,peak:c.$a,rms:c.$d,binCount:c.l.frequencyBinCount,freqBins:c.Nd}))});0===a.length&&0===this.Ra.size&&this.Vb&&(this.m.Cd(this.ee),this.Vb=!1)}static He(b){return b*eb}static qd(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static Fe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Ca.Ib(self.gb);"use strict";function Cb(b){b.Yb||(b.Yb=b.Cc());return b.Yb}self.md=class{constructor(b,a,c,d,e){this.v=b;this.lf=a;this.La=c;this.T=d;this.gf=e;this.Kc="";this.Yb=null}j(){this.Yb=this.v=null}Cc(){}V(){return this.v.V()}sc(){return this.lf}jb(){return this.La}qc(){return this.T}Ba(){return this.gf}fa(){}};"use strict";
self.ue=class extends self.md{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Kc="html5";this.L=new Audio;this.L.crossOrigin="anonymous";this.L.autoplay=!1;this.L.preload="auto";this.yb=this.zb=null;this.L.addEventListener("canplaythrough",()=>!0);this.Cb=this.V().createGain();this.Bb=null;this.L.addEventListener("canplay",()=>{this.zb&&(this.zb(),this.yb=this.zb=null);!this.Bb&&this.L&&(this.Bb=this.V().createMediaElementSource(this.L),this.Bb.connect(this.Cb))});this.onended=null;this.L.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.L.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.La}' error: `,f);this.yb&&(this.yb(f),this.yb=this.zb=null)})}j(){Hb(this.v,this);this.Cb.disconnect();this.Cb=null;this.Bb.disconnect();this.Bb=null;this.L&&!this.L.paused&&this.L.pause();this.L=this.onended=null;super.j()}Cc(){return new Promise((b,a)=>{this.zb=b;this.yb=a;this.L.src=this.La})}W(){return this.L}fa(){return this.L.duration}};"use strict";
async function Lb(b){if(b.Ia)return b.Ia;var a=b.v.m;if("cordova"===a.u&&a.td(b.La)&&a.Wb)b.Ia=await a.Jb(b.La);else{a=await fetch(b.La);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Ia=await a.arrayBuffer()}}async function Mb(b){if(b.ha)return b.ha;b.ha=await Gb(b.v,b.Ia,b.kf);b.Ia=null}
self.we=class extends self.md{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Kc="webaudio";this.ha=this.Ia=null;this.kf=!!f}j(){Hb(this.v,this);this.ha=this.Ia=null;super.j()}async Cc(){try{await Lb(this),await Mb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.La}': `,b)}}fa(){return this.ha?this.ha.duration:0}};"use strict";let Nb=0;
function Q(b,a){a=!!a;b.vb!==a&&(b.vb=a,b.vb?(R(b,!1),b.F||(b.F=b.V().createPanner(),b.F.panningModel=b.v.Yd,b.F.distanceModel=b.v.Id,b.F.refDistance=b.v.Zd,b.F.maxDistance=b.v.Xd,b.F.rolloffFactor=b.v.ae),b.G.disconnect(),b.G.connect(b.F),b.F.connect(b.ea())):(b.F.disconnect(),b.G.disconnect(),b.G.connect(b.ea())))}
function R(b,a){a=!!a;b.Xb!==a&&(b.Xb=a,b.Xb?(Q(b,!1),b.ca=b.V().createStereoPanner(),b.G.disconnect(),b.G.connect(b.ca),b.ca.connect(b.ea())):(b.ca.disconnect(),b.ca=null,b.G.disconnect(),b.G.connect(b.ea())))}function nb(b,a){b.Xb&&b.cd!==a&&(b.ca.pan.value=a,b.cd=a)}function U(b,a){b.Ma=a;b.G.gain.cancelScheduledValues(0);b.Va=-1;b.G.gain.value=b.tc()}function Kb(b,a){a=!!a;b.va!==a&&(b.va=a,b.Qb())}
function mb(b,a,c,d,e){if(b.vb){var f=b.Za,g=b.Ya,h=Math.cos(e);e=Math.sin(e);if(f[0]!==a||f[1]!==c||f[2]!==d)f[0]=a,f[1]=c,f[2]=d,b.F.setPosition(...f);if(g[0]!==h||g[1]!==e||0!==g[2])g[0]=h,g[1]=e,g[2]=0,b.F.setOrientation(...g)}}function V(b){return b.Vc?b.v.Oc:performance.now()/1E3}
self.nd=class{constructor(b,a,c){this.v=b;this.P=a;this.na=c;this.Rb=Nb++;this.G=this.V().createGain();this.G.connect(this.ea());this.F=null;this.vb=!1;this.Za=[0,0,0];this.Ya=[0,0,0];this.sa=[0,0,0];this.ca=null;this.Xb=!1;this.cd=0;this.I=!0;this.Y=this.ta=this.J=!1;this.Ma=1;this.va=!1;this.la=1;b=this.v.fd;this.Vc=1===b&&!this.Ba()||2===b;this.Va=this.qa=-1;this.ce=!1}j(){this.P=this.v=null;this.F&&(this.F.disconnect(),this.F=null);this.ca&&(this.ca.disconnect(),this.ca=null);this.G.disconnect();
this.G=null}V(){return this.v.V()}ea(){return Eb(this.v,0<this.na.length?this.na[0]:"")}sc(){return this.P.sc()}jb(){return this.P.jb()}qc(){return this.P.qc()}Ba(){return this.P.Ba()}O(){}oc(){}IsPlaying(){return!this.I&&!this.J&&!this.O()}Na(){}fa(){return this.P.fa()}Play(){}Da(){}mb(){}Lb(){}Pa(b){-1!==this.Va&&b>=this.Va&&(this.Va=-1,this.ce&&this.Da(),Ib(this.v,"fade-ended",this.na,this.Rb))}tc(){const b=this.Ma;return isFinite(b)?b:0}Kb(){return this.v.Kb()}Qb(){}wc(){}Ga(){}vc(){}xc(){}uc(){}ib(){var b=
this.Rb,a=this.na,c=this.fa(),d=-1===this.Va?this.Ma:this.G.gain.value,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.Za,orient:this.Ya,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.qa}}else f=null;return{aiid:b,tags:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Na(),playbackRate:this.la,uid:this.qa,bufferOriginalUrl:this.sc(),bufferUrl:"",bufferType:this.qc(),isMusic:this.Ba(),isLooping:this.Y,isMuted:this.va,resumePosition:this.uc(),pan:f,stereoPan:this.ca?
this.cd:null}}Dc(b){var a=b.playbackRate;this.la!==a&&(this.la=a,this.Ga());Kb(this,b.isMuted)}};"use strict";
self.ve=class extends self.nd{constructor(b,a,c){super(b,a,c);this.P.Cb.connect(this.G);this.P.onended=()=>this.Fc()}j(){this.Da();this.P.Cb.disconnect();super.j()}W(){return this.P.W()}Fc(){this.I=!0;this.qa=-1;Ib(this.v,"ended",this.na,this.Rb)}O(){return this.W().ended}oc(){return this.I?!0:this.O()}Na(){let b=this.W().currentTime;this.Y||(b=Math.min(b,this.fa()));return b}Play(b,a,c){const d=this.W();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);U(this,a);this.va=!1;d.muted&&(d.muted=
!1);if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.P.jb()}' to position '${c}': `,e)}this.v.Ea(d);this.J=this.I=!1;this.Y=b;this.la=1}Da(){const b=this.W();b.paused||b.pause();this.v.Oa(b);this.I=!0;this.J=!1;this.qa=-1}mb(){if(!(this.J||this.I||this.O())){var b=this.W();b.paused||b.pause();this.v.Oa(b);this.J=!0}}Lb(){!this.J||this.I||this.O()||(this.v.Ea(this.W()),this.J=!1)}Qb(){this.W().muted=this.va||this.Kb()}wc(b){b=!!b;this.Y!==
b&&(this.Y=b,this.W().loop=b)}Ga(){let b=this.la;this.Vc&&(b*=this.v.kc);try{this.W().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}vc(b){if(!this.I&&!this.O())try{this.W().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}uc(){return this.Na()}xc(b){b?this.IsPlaying()?(this.W().pause(),this.ta=!0):this.ta=!1:this.ta&&(this.v.Ea(this.W()),this.ta=!1)}};"use strict";
function W(b){b.s&&(b.s.onended=null,b.s.disconnect(),b.s.buffer=null);b.s=null;b.ob=null}
self.xe=class extends self.nd{constructor(b,a,c){super(b,a,c);this.s=null;this.bc=d=>this.Fc(d);this.Pc=!0;this.ob=null;this.S=this.dc=this.fc=0;this.Zc=1}j(){this.Da();W(this);this.bc=null;super.j()}Fc(b){this.J||this.ta||b.target!==this.ob||(this.I=this.Pc=!0,this.qa=-1,W(this),Ib(this.v,"ended",this.na,this.Rb))}O(){return!this.I&&this.s&&this.s.loop||this.J?!1:this.Pc}oc(){return!this.s||this.I?!0:this.O()}Na(){let b;b=this.J?this.S:this.dc+(V(this)-this.fc)*this.la;this.Y||(b=Math.min(b,this.fa()));
return b}Play(b,a,c,d){this.va=!1;this.Zc=1;U(this,a);W(this);this.s=this.V().createBufferSource();this.s.buffer=this.P.ha;this.s.connect(this.G);this.ob=this.s;this.s.onended=this.bc;this.s.loop=b;this.s.start(d,c);this.J=this.I=this.Pc=!1;this.Y=b;this.la=1;this.fc=V(this);this.dc=c}Da(){if(this.s)try{this.s.stop(0)}catch(b){}this.I=!0;this.J=!1;this.qa=-1}mb(){this.J||this.I||this.O()||(this.S=this.Na(),this.Y&&(this.S%=this.fa()),this.J=!0,this.s.stop(0))}Lb(){!this.J||this.I||this.O()||(W(this),
this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.ob=this.s,this.s.onended=this.bc,this.s.loop=this.Y,U(this,this.Ma),this.Ga(),this.s.start(0,this.S),this.fc=V(this),this.dc=this.S,this.J=!1)}tc(){return super.tc()*this.Zc}Qb(){this.Zc=this.va||this.Kb()?0:1;U(this,this.Ma)}wc(b){b=!!b;this.Y!==b&&(this.Y=b,this.s&&(this.s.loop=b))}Ga(){let b=this.la;this.Vc&&(b*=this.v.kc);this.s&&(this.s.playbackRate.value=b)}vc(b){this.I||this.O()||(this.J?this.S=b:(this.mb(),
this.S=b,this.Lb()))}uc(){return this.S}xc(b){b?this.IsPlaying()?(this.ta=!0,this.S=this.Na(),this.Y&&(this.S%=this.fa()),this.s.stop(0)):this.ta=!1:this.ta&&(W(this),this.s=this.V().createBufferSource(),this.s.buffer=this.P.ha,this.s.connect(this.G),this.ob=this.s,this.s.onended=this.bc,this.s.loop=this.Y,U(this,this.Ma),this.Ga(),this.s.start(0,this.S),this.fc=V(this),this.dc=this.S,this.ta=!1)}Dc(b){super.Dc(b);this.S=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.v=b;this.g=b.V();this.Rd=-1;this.T=this.dd="";this.o=null}j(){this.g=null}N(){}U(){}ib(){return{type:this.T,tag:this.dd,params:this.o}}}
self.ne=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.o=[a,c,d,e,f,g];this.A=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.D=this.g.createBiquadFilter();this.D.type=a;this.D.frequency.value=c;this.D.detune.value=d;this.D.Q.value=e;this.D.gain.vlaue=f;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i)}j(){this.A.disconnect();this.D.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.o[1]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[2]=a;Y(this,this.D.detune,a,c,d);break;case 3:this.o[3]=a;Y(this,this.D.Q,a,c,d);break;case 4:this.o[4]=a,Y(this,this.D.gain,a,c,d)}}};
self.le=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.o=[a,c,d];this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.Ab=X(this);this.X=this.g.createDelay(a);this.X.delayTime.value=a;this.tb=X(this);this.tb.gain.value=c;this.A.connect(this.Ab);this.A.connect(this.h);this.Ab.connect(this.i);this.Ab.connect(this.X);this.X.connect(this.tb);this.tb.connect(this.Ab)}j(){this.A.disconnect();this.i.disconnect();this.h.disconnect();this.Ab.disconnect();
this.X.disconnect();this.tb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){const e=self.gb.qd;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.o[1]=e(a);Y(this,this.tb.gain,e(a),c,d);break;case 5:this.o[0]=a,Y(this,this.X.delayTime,a,c,d)}}};
self.ke=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.o=[c,d];this.Hd=this.Gd="";this.A=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.sb=this.g.createConvolver();this.sb.normalize=c;this.sb.buffer=a;this.A.connect(this.sb);this.A.connect(this.h);this.sb.connect(this.i)}j(){this.A.disconnect();this.sb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}ib(){const b=super.ib();b.bufferOriginalUrl=this.Gd;b.bufferUrl="";b.bufferType=this.Hd;return b}};
self.oe=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.o=[a,c,d,e,f];this.A=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.ub=X(this);this.ub.gain.value=e;this.X=this.g.createDelay(a+c);this.X.delayTime.value=a;this.C=this.g.createOscillator();this.C.frequency.value=d;this.K=X(this);this.K.gain.value=c;this.A.connect(this.X);this.A.connect(this.h);this.X.connect(this.i);this.X.connect(this.ub);this.ub.connect(this.X);this.C.connect(this.K);
this.K.connect(this.X.delayTime);this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.X.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();this.ub.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.o[1]=a/1E3;Y(this,this.K.gain,a/1E3,
c,d);break;case 7:this.o[2]=a;Y(this,this.C.frequency,a,c,d);break;case 8:this.o[3]=a/100,Y(this,this.ub.gain,a/100,c,d)}}};
self.qe=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.o=[a,c,d,e,f,g];this.A=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.D=this.g.createBiquadFilter();this.D.type="allpass";this.D.frequency.value=a;this.D.detune.value=c;this.D.Q.value=d;this.C=this.g.createOscillator();this.C.frequency.value=f;this.K=X(this);this.K.gain.value=e;this.A.connect(this.D);this.A.connect(this.h);this.D.connect(this.i);this.C.connect(this.K);this.K.connect(this.D.frequency);
this.C.start(0)}j(){this.C.stop(0);this.A.disconnect();this.D.disconnect();this.C.disconnect();this.K.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.o[0]=a;Y(this,this.D.frequency,a,c,d);break;case 2:this.o[1]=a;Y(this,this.D.detune,a,c,d);
break;case 3:this.o[2]=a;Y(this,this.D.Q,a,c,d);break;case 6:this.o[3]=a;Y(this,this.K.gain,a,c,d);break;case 7:this.o[4]=a,Y(this,this.C.frequency,a,c,d)}}};self.pe=class extends Z{constructor(b,a){super(b);this.T="gain";this.o=[a];this.l=X(this);this.l.gain.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){const e=self.gb.qd;switch(b){case 4:this.o[0]=e(a),Y(this,this.l.gain,e(a),c,d)}}};
self.se=class extends Z{constructor(b,a){super(b);this.T="stereopan";this.o=[a];this.l=this.g.createStereoPanner();this.l.pan.value=a}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){a=Math.min(Math.max(a/100,-1),1);switch(b){case 9:this.o[0]=a,Y(this,this.l.pan,a,c,d)}}};
self.te=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.o=[a,c];this.l=X(this);this.l.gain.value=1-c/2;this.C=this.g.createOscillator();this.C.frequency.value=a;this.K=X(this);this.K.gain.value=c/2;this.C.connect(this.K);this.K.connect(this.l.gain);this.C.start(0)}j(){this.C.stop(0);this.C.disconnect();this.K.disconnect();this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=
a;Y(this,this.l.gain,1-a/2,c,d);Y(this,this.K.gain,a/2,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.re=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.o=[a,c];this.A=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.Fb=X(this);this.Fb.gain.value=0;this.C=this.g.createOscillator();this.C.frequency.value=a;this.C.connect(this.Fb.gain);this.C.start(0);this.A.connect(this.Fb);this.A.connect(this.h);this.Fb.connect(this.i)}j(){this.C.stop(0);this.C.disconnect();this.Fb.disconnect();this.A.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.o[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.o[0]=a,Y(this,this.C.frequency,a,c,d)}}};
self.me=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.o=[a,c,d,e,f];this.A=X(this);this.ic=X(this);this.hc=X(this);b=d;.01>b&&(b=.01);this.ic.gain.value=b;this.hc.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.lc=this.g.createWaveShaper();this.Lc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Lc[32768+e]=f,this.Lc[32768-
e-1]=-f;this.lc.curve=this.Lc;this.A.connect(this.ic);this.A.connect(this.h);this.ic.connect(this.lc);this.lc.connect(this.hc);this.hc.connect(this.i)}j(){this.A.disconnect();this.ic.disconnect();this.lc.disconnect();this.hc.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}N(){return this.A}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.o[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.je=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.o=[a,c,d,e,f];this.l=this.g.createDynamicsCompressor();this.l.threshold.value=a;this.l.knee.value=c;this.l.ratio.value=d;this.l.attack.value=e;this.l.release.value=f}j(){this.l.disconnect();super.j()}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
self.ie=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.o=[a,c];this.l=this.g.createAnalyser();this.l.fftSize=a;this.l.smoothingTimeConstant=c;this.Nd=new Float32Array(this.l.frequencyBinCount);this.be=new Uint8Array(a);this.$d=this.$a=0;b=this.v;b.Ra.add(this);T(b)}j(){this.v.Ra.delete(this);this.l.disconnect();super.j()}Pa(){this.l.getFloatFrequencyData(this.Nd);this.l.getByteTimeDomainData(this.be);const b=this.l.fftSize;let a=this.$a=0;for(var c=0;c<b;++c){let d=(this.be[c]-
128)/128;0>d&&(d=-d);this.$a<d&&(this.$a=d);a+=d*d}c=self.gb.Fe;this.$a=c(this.$a);this.$d=c(Math.sqrt(a/b))}U(b){this.l.disconnect();this.l.connect(b)}N(){return this.l}Z(){}};
